import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google";

// const Montserrat = localFont({
//   src: "../../public/Montserrat-Black.ttf",
//   variable: "--font-geist-sans",
//   weight: "400",
// });
// const MontserratMedium = localFont({
//   src: "../../public/Montserrat-Medium.ttf",
//   variable: "--font-geist",
//   weight: "500",
// });
// const Montserratsemibold = localFont({
//   src: "../../public/Montserrat-SemiBold.ttf",
//   variable: "--font-asad",
//   weight: "600",
// });
// const Montserratbold = localFont({
//   src: "../../public/Montserrat-Bold.ttf",
//   variable: "--font-ali",
//   weight: "700",
// });
// export const metadata = {
//   title: "asad",
//   description: "Generated by create next app",
// };

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`  antialiased`}>
        <div className={montserrat.variable}>
          <div className="font-sans">{children}</div>
        </div>
      </body>
    </html>
  );
}
